# -*- coding: utf-8 -*-
"""continue_and_break.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wxY1MMYWzpwQodJZqShXEJ1FRgqoJ_Ct
"""

# Continue Examples

#Case 1: Continue is used after the 1 statement.So only the statements above the continue will be able to print, rest will not be printing.
list = [1,2,3,4]
n = len(list)
for  i in range(n):
  print("This is 1st sentense")
  continue
  print("This is 2nd Sentense")
  print("This is the 3rd sentense just after the continue")
  print("This is  the 4th sentense")
  print("This is  the 5th sentense")

#Case 2: Continue is used after the 2 statements.So only the statements above the continue will be able to print, rest will not be printing.
list = [1,2,3,4]
n = len(list)
for  i in range(n):
  print("This is 1st sentense")
  print("This is 2nd Sentense")
  continue
  print("This is the 3rd sentense just after the continue")
  print("This is  the 4th sentense")
  print("This is  the 5th sentense")

#Case 3: Continue is used after the 3 statements.So only the statements above the continue will be able to print, rest will not be printing.
list = [1,2,3,4]
n = len(list)
for  i in range(n):
  print("This is 1st sentense")
  print("This is 2nd Sentense")
  print("This is the 3rd sentense just after the continue")
  continue
  print("This is  the 4th sentense")
  print("This is  the 5th sentense")

#Case 4: Continue is used after the 4 statements.So only the statements above the continue will be able to print, rest will not be printing.
list = [1,2,3,4]
n = len(list)
for  i in range(n):
  print("This is 1st sentense")
  print("This is 2nd Sentense")
  print("This is the 3rd sentense just after the continue")
  print("This is  the 4th sentense")
  continue
  print("This is  the 5th sentense")

#Case 5: Continue is used after the 5 statements.So only the statements above the continue will be able to print, rest will not be printing.
list = [1,2,3,4]
n = len(list)
for  i in range(n):
  print("This is 1st sentense")
  print("This is 2nd Sentense")
  print("This is the 3rd sentense just after the continue")
  print("This is  the 4th sentense")
  print("This is  the 5th sentense")
  continue

# Break Examples

#Case 1: Break is used after the 1 statement.So only the statements above the continue will be able to print, rest will not be printing.
list = [1,2,3,4]
n = len(list)
for  i in range(n):
  print("This is 1st sentense")
  break
  print("This is 2nd Sentense")
  print("This is the 3rd sentense just after the continue")
  print("This is  the 4th sentense")
  print("This is  the 5th sentense")

#Case 2: Break is used after the 2 statements.So only the statements above the continue will be able to print, rest will not be printing.
list = [1,2,3,4]
n = len(list)
for  i in range(n):
  print("This is 1st sentense")
  print("This is 2nd Sentense")
  break
  print("This is the 3rd sentense just after the continue")
  print("This is  the 4th sentense")
  print("This is  the 5th sentense")

#Case 3: Break is used after the 3 statements.So only the statements above the continue will be able to print, rest will not be printing.
list = [1,2,3,4]
n = len(list)
for  i in range(n):
  print("This is 1st sentense")
  print("This is 2nd Sentense")
  print("This is the 3rd sentense just after the continue")
  break
  print("This is  the 4th sentense")
  print("This is  the 5th sentense")

#Case 4: Break is used after the 4 statements.So only the statements above the continue will be able to print, rest will not be printing.
list = [1,2,3,4]
n = len(list)
for  i in range(n):
  print("This is 1st sentense")
  print("This is 2nd Sentense")
  print("This is the 3rd sentense just after the continue")
  print("This is  the 4th sentense")
  break
  print("This is  the 5th sentense")

#Case 5: Break is used after the 5 statements.So only the statements above the continue will be able to print, rest will not be printing.
list = [1,2,3,4]
n = len(list)
for  i in range(n):
  print("This is 1st sentense")
  print("This is 2nd Sentense")
  print("This is the 3rd sentense just after the continue")
  print("This is  the 4th sentense")
  print("This is  the 5th sentense")
  break

# Impotance of break statements. 
# Prime Number Example

# Case 1 ---> Prime Number Code  where break is not used.

num = int(input("Enter the number: "))
count = 1
for number in range(2,num):
  count = count + 1
 # print("The value of number is {}".format(number))
 # print("The value of num is {}".format(num))
  rem = (num % number)
  print("The value of remainder for the number {} is {}".format(count,rem))
  if rem == 0:
    print("It is not a Prime number")
else:
  print("prime number")

# Case 2 ---> Prime Number Code  where break is used.

num = int(input("Enter the number: "))
count = 1
for number in range(2,num):
  count = count + 1
 # print("The value of number is {}".format(number))
 # print("The value of num is {}".format(num))
  rem = (num % number)
  print("The value of remainder for the number {} is {}".format(count,rem))
  if rem == 0:
    print("It is not a Prime number")
    break
else:
  print("prime number")